# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptiClassMain(object):
    def setupUi(self, OptiClassMain):
        OptiClassMain.setObjectName("OptiClassMain")
        OptiClassMain.resize(578, 683)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptiClassMain)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(OptiClassMain)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_2.addWidget(self.radioButton_6)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_3.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_3.addWidget(self.radioButton_9)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_5.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_5.addWidget(self.radioButton_11)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_12.setChecked(True)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_6.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_6.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_6.addWidget(self.radioButton_14)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_23 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_23.setObjectName("radioButton_23")
        self.verticalLayout_12.addWidget(self.radioButton_23)
        self.radioButton_22 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_22.setObjectName("radioButton_22")
        self.verticalLayout_12.addWidget(self.radioButton_22)
        self.radioButton_21 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_21.setObjectName("radioButton_21")
        self.verticalLayout_12.addWidget(self.radioButton_21)
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_20.setObjectName("radioButton_20")
        self.verticalLayout_12.addWidget(self.radioButton_20)
        self.horizontalLayout_15.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_6)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_7.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_7)
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_8)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_13)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_14.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_14.addWidget(self.pushButton_9)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_14.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_8.setAcceptDrops(False)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_3.addWidget(self.checkBox_11)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_4.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_4.addWidget(self.checkBox_16)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_4.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_4.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_4.addWidget(self.checkBox_14)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_18.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_5.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_5.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_5.addWidget(self.checkBox_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_8.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_8.addWidget(self.checkBox_10)
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_8.addWidget(self.checkBox_17)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_18.addWidget(self.groupBox_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_10.addWidget(self.pushButton_5)
        self.verticalLayout_18.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.verticalLayout_14.addWidget(self.groupBox_11)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_5)
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_11.addWidget(self.textEdit)
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioButton_15 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_15.setChecked(True)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_12.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_16.setObjectName("radioButton_16")
        self.horizontalLayout_12.addWidget(self.radioButton_16)
        self.radioButton_17 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_17.setObjectName("radioButton_17")
        self.horizontalLayout_12.addWidget(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_18.setObjectName("radioButton_18")
        self.horizontalLayout_12.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_19.setObjectName("radioButton_19")
        self.horizontalLayout_12.addWidget(self.radioButton_19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_13.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_13.addWidget(self.pushButton_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_12 = QtWidgets.QPushButton(OptiClassMain)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_8.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(OptiClassMain)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_8.addWidget(self.pushButton_11)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(OptiClassMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OptiClassMain)

    def retranslateUi(self, OptiClassMain):
        _translate = QtCore.QCoreApplication.translate
        OptiClassMain.setWindowTitle(_translate("OptiClassMain", "OptiClass"))
        self.groupBox.setTitle(_translate("OptiClassMain", "Place"))
        self.comboBox.setItemText(0, _translate("OptiClassMain", "All Region"))
        self.comboBox.setItemText(1, _translate("OptiClassMain", "Asia"))
        self.comboBox_2.setItemText(0, _translate("OptiClassMain", "All Country"))
        self.comboBox_2.setItemText(1, _translate("OptiClassMain", "Thailand"))
        self.comboBox_2.setItemText(2, _translate("OptiClassMain", "Japan"))
        self.comboBox_3.setItemText(0, _translate("OptiClassMain", "All Hospital"))
        self.comboBox_3.setItemText(1, _translate("OptiClassMain", "Churabhon Hospital"))
        self.comboBox_4.setItemText(0, _translate("OptiClassMain", "All Device"))
        self.comboBox_4.setItemText(1, _translate("OptiClassMain", "Device 1"))
        self.groupBox_2.setTitle(_translate("OptiClassMain", "Period"))
        self.radioButton.setText(_translate("OptiClassMain", "All"))
        self.radioButton_2.setText(_translate("OptiClassMain", "1y"))
        self.radioButton_3.setText(_translate("OptiClassMain", "0.5y"))
        self.radioButton_4.setText(_translate("OptiClassMain", "1m"))
        self.radioButton_5.setText(_translate("OptiClassMain", "1w"))
        self.radioButton_6.setText(_translate("OptiClassMain", "1d"))
        self.groupBox_3.setTitle(_translate("OptiClassMain", "Gender"))
        self.radioButton_7.setText(_translate("OptiClassMain", "All"))
        self.radioButton_8.setText(_translate("OptiClassMain", "Female"))
        self.radioButton_9.setText(_translate("OptiClassMain", "Male"))
        self.groupBox_4.setTitle(_translate("OptiClassMain", "Range of age"))
        self.label.setText(_translate("OptiClassMain", "  to  "))
        self.groupBox_5.setTitle(_translate("OptiClassMain", "Optical data"))
        self.radioButton_10.setText(_translate("OptiClassMain", "Ulna"))
        self.radioButton_11.setText(_translate("OptiClassMain", "Radius"))
        self.checkBox.setText(_translate("OptiClassMain", "Phantom"))
        self.groupBox_6.setTitle(_translate("OptiClassMain", "Measured arm"))
        self.radioButton_12.setText(_translate("OptiClassMain", "All"))
        self.radioButton_13.setText(_translate("OptiClassMain", "Left"))
        self.radioButton_14.setText(_translate("OptiClassMain", "Right"))
        self.pushButton_2.setText(_translate("OptiClassMain", "Default"))
        self.pushButton_4.setText(_translate("OptiClassMain", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OptiClassMain", "Optical"))
        self.groupBox_10.setTitle(_translate("OptiClassMain", "Bone"))
        self.radioButton_23.setText(_translate("OptiClassMain", "Ulna"))
        self.radioButton_22.setText(_translate("OptiClassMain", "Radius"))
        self.radioButton_21.setText(_translate("OptiClassMain", "Femur"))
        self.radioButton_20.setText(_translate("OptiClassMain", "Lumber"))
        self.comboBox_6.setItemText(0, _translate("OptiClassMain", "UD"))
        self.comboBox_6.setItemText(1, _translate("OptiClassMain", "33%"))
        self.comboBox_6.setItemText(2, _translate("OptiClassMain", "Total"))
        self.comboBox_7.setItemText(0, _translate("OptiClassMain", "UD"))
        self.comboBox_7.setItemText(1, _translate("OptiClassMain", "33%"))
        self.comboBox_7.setItemText(2, _translate("OptiClassMain", "Total"))
        self.comboBox_8.setItemText(0, _translate("OptiClassMain", "Neck"))
        self.comboBox_8.setItemText(1, _translate("OptiClassMain", "Upper Neck"))
        self.comboBox_8.setItemText(2, _translate("OptiClassMain", "Lower Neck"))
        self.comboBox_8.setItemText(3, _translate("OptiClassMain", "Troch"))
        self.comboBox_8.setItemText(4, _translate("OptiClassMain", "Shaft"))
        self.comboBox_8.setItemText(5, _translate("OptiClassMain", "Total"))
        self.comboBox_9.setItemText(0, _translate("OptiClassMain", "L1"))
        self.comboBox_9.setItemText(1, _translate("OptiClassMain", "L2"))
        self.comboBox_9.setItemText(2, _translate("OptiClassMain", "L3"))
        self.comboBox_9.setItemText(3, _translate("OptiClassMain", "L4"))
        self.comboBox_9.setItemText(4, _translate("OptiClassMain", "L1 - L2"))
        self.comboBox_9.setItemText(5, _translate("OptiClassMain", "L1 - L3"))
        self.comboBox_9.setItemText(6, _translate("OptiClassMain", "L1 - L4"))
        self.comboBox_9.setItemText(7, _translate("OptiClassMain", "L2 - L3"))
        self.comboBox_9.setItemText(8, _translate("OptiClassMain", "L2 - L4"))
        self.comboBox_9.setItemText(9, _translate("OptiClassMain", "L3 - L4"))
        self.comboBox_9.setItemText(10, _translate("OptiClassMain", "Maximum Total"))
        self.pushButton_8.setText(_translate("OptiClassMain", "Default"))
        self.pushButton_9.setText(_translate("OptiClassMain", "Set"))
        self.groupBox_11.setTitle(_translate("OptiClassMain", "Other Infomation"))
        self.groupBox_8.setTitle(_translate("OptiClassMain", "Patient baisic infomation"))
        self.checkBox_2.setText(_translate("OptiClassMain", "Age"))
        self.checkBox_11.setText(_translate("OptiClassMain", "Dominant hand"))
        self.checkBox_3.setText(_translate("OptiClassMain", "BMI"))
        self.checkBox_4.setText(_translate("OptiClassMain", "Hight"))
        self.checkBox_5.setText(_translate("OptiClassMain", "Weight"))
        self.checkBox_15.setText(_translate("OptiClassMain", "Diabetes"))
        self.checkBox_16.setText(_translate("OptiClassMain", "Dialysis"))
        self.checkBox_12.setText(_translate("OptiClassMain", "Fracture of measurement point"))
        self.checkBox_13.setText(_translate("OptiClassMain", "Artifical bone"))
        self.checkBox_14.setText(_translate("OptiClassMain", "Drug for osteoporosis "))
        self.groupBox_9.setTitle(_translate("OptiClassMain", "FRAX®"))
        self.checkBox_6.setText(_translate("OptiClassMain", "Privious fracture"))
        self.checkBox_7.setText(_translate("OptiClassMain", "Current smoking"))
        self.checkBox_8.setText(_translate("OptiClassMain", "Seconfary osteoporosis"))
        self.checkBox_9.setText(_translate("OptiClassMain", "Palental fractured hip"))
        self.checkBox_10.setText(_translate("OptiClassMain", "Rheumatpid arthntis"))
        self.checkBox_17.setText(_translate("OptiClassMain", "Alcohol 3 or more units per day"))
        self.pushButton_3.setText(_translate("OptiClassMain", "Clear All"))
        self.pushButton_5.setText(_translate("OptiClassMain", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OptiClassMain", "Bone"))
        self.label_4.setText(_translate("OptiClassMain", "Machine learning model"))
        self.comboBox_5.setItemText(0, _translate("OptiClassMain", "Gradient Boosting Classifier"))
        self.comboBox_5.setItemText(1, _translate("OptiClassMain", "K-Neighbors Classifier"))
        self.comboBox_5.setItemText(2, _translate("OptiClassMain", "SVC"))
        self.comboBox_5.setItemText(3, _translate("OptiClassMain", "Random Forest Classifier"))
        self.comboBox_5.setItemText(4, _translate("OptiClassMain", "BAgging classifier"))
        self.comboBox_5.setItemText(5, _translate("OptiClassMain", "Slope classifier"))
        self.label_2.setText(_translate("OptiClassMain", "Parameter"))
        self.label_3.setText(_translate("OptiClassMain", "Cross validation"))
        self.radioButton_15.setText(_translate("OptiClassMain", "LOO"))
        self.radioButton_16.setText(_translate("OptiClassMain", "5%"))
        self.radioButton_17.setText(_translate("OptiClassMain", "10%"))
        self.radioButton_18.setText(_translate("OptiClassMain", "20%"))
        self.radioButton_19.setText(_translate("OptiClassMain", "30%"))
        self.pushButton_7.setText(_translate("OptiClassMain", "Default"))
        self.pushButton_6.setText(_translate("OptiClassMain", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("OptiClassMain", "Machine laering"))
        self.pushButton_12.setText(_translate("OptiClassMain", "Basic analysis"))
        self.pushButton_11.setText(_translate("OptiClassMain", "Machine learning"))

