# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptiClassMain(object):
    def setupUi(self, OptiClassMain):
        OptiClassMain.setObjectName("OptiClassMain")
        OptiClassMain.resize(631, 665)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptiClassMain)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(OptiClassMain)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_place = QtWidgets.QGroupBox(self.tab)
        self.groupBox_place.setFlat(False)
        self.groupBox_place.setCheckable(False)
        self.groupBox_place.setObjectName("groupBox_place")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_place)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_region = QtWidgets.QComboBox(self.groupBox_place)
        self.comboBox_region.setObjectName("comboBox_region")
        self.comboBox_region.addItem("")
        self.comboBox_region.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_region)
        self.comboBox_country = QtWidgets.QComboBox(self.groupBox_place)
        self.comboBox_country.setObjectName("comboBox_country")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.comboBox_country.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_country)
        self.comboBox_hospital = QtWidgets.QComboBox(self.groupBox_place)
        self.comboBox_hospital.setObjectName("comboBox_hospital")
        self.comboBox_hospital.addItem("")
        self.comboBox_hospital.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_hospital)
        self.comboBox_device = QtWidgets.QComboBox(self.groupBox_place)
        self.comboBox_device.setObjectName("comboBox_device")
        self.comboBox_device.addItem("")
        self.comboBox_device.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_device)
        self.verticalLayout_2.addWidget(self.groupBox_place)
        self.groupBox_period = QtWidgets.QGroupBox(self.tab)
        self.groupBox_period.setObjectName("groupBox_period")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_period)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_periodAll = QtWidgets.QRadioButton(self.groupBox_period)
        self.radioButton_periodAll.setChecked(True)
        self.radioButton_periodAll.setObjectName("radioButton_periodAll")
        self.horizontalLayout_2.addWidget(self.radioButton_periodAll)
        self.radioButton_period1y = QtWidgets.QRadioButton(self.groupBox_period)
        self.radioButton_period1y.setObjectName("radioButton_period1y")
        self.horizontalLayout_2.addWidget(self.radioButton_period1y)
        self.radioButton_period05y = QtWidgets.QRadioButton(self.groupBox_period)
        self.radioButton_period05y.setObjectName("radioButton_period05y")
        self.horizontalLayout_2.addWidget(self.radioButton_period05y)
        self.radioButton_period1m = QtWidgets.QRadioButton(self.groupBox_period)
        self.radioButton_period1m.setObjectName("radioButton_period1m")
        self.horizontalLayout_2.addWidget(self.radioButton_period1m)
        self.radioButton_period1w = QtWidgets.QRadioButton(self.groupBox_period)
        self.radioButton_period1w.setObjectName("radioButton_period1w")
        self.horizontalLayout_2.addWidget(self.radioButton_period1w)
        self.radioButton_period1d = QtWidgets.QRadioButton(self.groupBox_period)
        self.radioButton_period1d.setObjectName("radioButton_period1d")
        self.horizontalLayout_2.addWidget(self.radioButton_period1d)
        self.verticalLayout_2.addWidget(self.groupBox_period)
        self.groupBox_gender = QtWidgets.QGroupBox(self.tab)
        self.groupBox_gender.setObjectName("groupBox_gender")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_gender)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_genderAll = QtWidgets.QRadioButton(self.groupBox_gender)
        self.radioButton_genderAll.setChecked(True)
        self.radioButton_genderAll.setObjectName("radioButton_genderAll")
        self.horizontalLayout_3.addWidget(self.radioButton_genderAll)
        self.radioButton_genderF = QtWidgets.QRadioButton(self.groupBox_gender)
        self.radioButton_genderF.setObjectName("radioButton_genderF")
        self.horizontalLayout_3.addWidget(self.radioButton_genderF)
        self.radioButton_genderM = QtWidgets.QRadioButton(self.groupBox_gender)
        self.radioButton_genderM.setObjectName("radioButton_genderM")
        self.horizontalLayout_3.addWidget(self.radioButton_genderM)
        self.verticalLayout_2.addWidget(self.groupBox_gender)
        self.groupBox_age = QtWidgets.QGroupBox(self.tab)
        self.groupBox_age.setObjectName("groupBox_age")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_age)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_rangeAge1 = QtWidgets.QLineEdit(self.groupBox_age)
        self.lineEdit_rangeAge1.setObjectName("lineEdit_rangeAge1")
        self.horizontalLayout_4.addWidget(self.lineEdit_rangeAge1)
        self.label = QtWidgets.QLabel(self.groupBox_age)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_rangeAge2 = QtWidgets.QLineEdit(self.groupBox_age)
        self.lineEdit_rangeAge2.setObjectName("lineEdit_rangeAge2")
        self.horizontalLayout_4.addWidget(self.lineEdit_rangeAge2)
        self.verticalLayout_2.addWidget(self.groupBox_age)
        self.groupBox_optdata = QtWidgets.QGroupBox(self.tab)
        self.groupBox_optdata.setObjectName("groupBox_optdata")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_optdata)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_optDataUlna = QtWidgets.QRadioButton(self.groupBox_optdata)
        self.radioButton_optDataUlna.setChecked(True)
        self.radioButton_optDataUlna.setObjectName("radioButton_optDataUlna")
        self.horizontalLayout_5.addWidget(self.radioButton_optDataUlna)
        self.radioButton_optDataRadius = QtWidgets.QRadioButton(self.groupBox_optdata)
        self.radioButton_optDataRadius.setObjectName("radioButton_optDataRadius")
        self.horizontalLayout_5.addWidget(self.radioButton_optDataRadius)
        self.checkBox_optDataPhantom = QtWidgets.QCheckBox(self.groupBox_optdata)
        self.checkBox_optDataPhantom.setObjectName("checkBox_optDataPhantom")
        self.horizontalLayout_5.addWidget(self.checkBox_optDataPhantom)
        self.verticalLayout_2.addWidget(self.groupBox_optdata)
        self.groupBox_arm = QtWidgets.QGroupBox(self.tab)
        self.groupBox_arm.setObjectName("groupBox_arm")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_arm)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_armAll = QtWidgets.QRadioButton(self.groupBox_arm)
        self.radioButton_armAll.setChecked(True)
        self.radioButton_armAll.setObjectName("radioButton_armAll")
        self.horizontalLayout_6.addWidget(self.radioButton_armAll)
        self.radioButton_armLeft = QtWidgets.QRadioButton(self.groupBox_arm)
        self.radioButton_armLeft.setObjectName("radioButton_armLeft")
        self.horizontalLayout_6.addWidget(self.radioButton_armLeft)
        self.radioButton_armRight = QtWidgets.QRadioButton(self.groupBox_arm)
        self.radioButton_armRight.setObjectName("radioButton_armRight")
        self.horizontalLayout_6.addWidget(self.radioButton_armRight)
        self.verticalLayout_2.addWidget(self.groupBox_arm)
        self.pushButton_optset = QtWidgets.QPushButton(self.tab)
        self.pushButton_optset.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_optset.setObjectName("pushButton_optset")
        self.verticalLayout_2.addWidget(self.pushButton_optset)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_bone = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_bone.setObjectName("groupBox_bone")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_bone)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_boneUlna = QtWidgets.QRadioButton(self.groupBox_bone)
        self.radioButton_boneUlna.setChecked(True)
        self.radioButton_boneUlna.setObjectName("radioButton_boneUlna")
        self.verticalLayout_12.addWidget(self.radioButton_boneUlna)
        self.radioButton_boneRadius = QtWidgets.QRadioButton(self.groupBox_bone)
        self.radioButton_boneRadius.setObjectName("radioButton_boneRadius")
        self.verticalLayout_12.addWidget(self.radioButton_boneRadius)
        self.radioButton_boneFemur = QtWidgets.QRadioButton(self.groupBox_bone)
        self.radioButton_boneFemur.setObjectName("radioButton_boneFemur")
        self.verticalLayout_12.addWidget(self.radioButton_boneFemur)
        self.radioButton_boneLumbar = QtWidgets.QRadioButton(self.groupBox_bone)
        self.radioButton_boneLumbar.setObjectName("radioButton_boneLumbar")
        self.verticalLayout_12.addWidget(self.radioButton_boneLumbar)
        self.horizontalLayout_15.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.comboBox_boneUlna = QtWidgets.QComboBox(self.groupBox_bone)
        self.comboBox_boneUlna.setObjectName("comboBox_boneUlna")
        self.comboBox_boneUlna.addItem("")
        self.comboBox_boneUlna.addItem("")
        self.comboBox_boneUlna.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_boneUlna)
        self.comboBox_boneRadius = QtWidgets.QComboBox(self.groupBox_bone)
        self.comboBox_boneRadius.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_boneRadius.setObjectName("comboBox_boneRadius")
        self.comboBox_boneRadius.addItem("")
        self.comboBox_boneRadius.addItem("")
        self.comboBox_boneRadius.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_boneRadius)
        self.comboBox_boneNeck = QtWidgets.QComboBox(self.groupBox_bone)
        self.comboBox_boneNeck.setObjectName("comboBox_boneNeck")
        self.comboBox_boneNeck.addItem("")
        self.comboBox_boneNeck.addItem("")
        self.comboBox_boneNeck.addItem("")
        self.comboBox_boneNeck.addItem("")
        self.comboBox_boneNeck.addItem("")
        self.comboBox_boneNeck.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_boneNeck)
        self.comboBox_boneLumbar = QtWidgets.QComboBox(self.groupBox_bone)
        self.comboBox_boneLumbar.setObjectName("comboBox_boneLumbar")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.comboBox_boneLumbar.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox_boneLumbar)
        self.horizontalLayout_15.addLayout(self.verticalLayout_13)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.pushButton_boneSet = QtWidgets.QPushButton(self.groupBox_bone)
        self.pushButton_boneSet.setObjectName("pushButton_boneSet")
        self.verticalLayout_17.addWidget(self.pushButton_boneSet)
        self.verticalLayout_14.addWidget(self.groupBox_bone)
        self.groupBox_other = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_other.setObjectName("groupBox_other")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_other)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_other)
        self.groupBox_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_8.setAcceptDrops(False)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_otherAge = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherAge.setObjectName("checkBox_otherAge")
        self.verticalLayout_3.addWidget(self.checkBox_otherAge)
        self.checkBox_otherHand = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherHand.setObjectName("checkBox_otherHand")
        self.verticalLayout_3.addWidget(self.checkBox_otherHand)
        self.checkBox_otherBmi = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherBmi.setObjectName("checkBox_otherBmi")
        self.verticalLayout_3.addWidget(self.checkBox_otherBmi)
        self.checkBox_otherHight = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherHight.setObjectName("checkBox_otherHight")
        self.verticalLayout_3.addWidget(self.checkBox_otherHight)
        self.checkBox_otherWeight = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherWeight.setObjectName("checkBox_otherWeight")
        self.verticalLayout_3.addWidget(self.checkBox_otherWeight)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_otherDiabates = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherDiabates.setObjectName("checkBox_otherDiabates")
        self.verticalLayout_4.addWidget(self.checkBox_otherDiabates)
        self.checkBox_otherDialysis = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherDialysis.setObjectName("checkBox_otherDialysis")
        self.verticalLayout_4.addWidget(self.checkBox_otherDialysis)
        self.checkBox_otherArmFrac = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherArmFrac.setObjectName("checkBox_otherArmFrac")
        self.verticalLayout_4.addWidget(self.checkBox_otherArmFrac)
        self.checkBox_otherArtifical = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherArtifical.setObjectName("checkBox_otherArtifical")
        self.verticalLayout_4.addWidget(self.checkBox_otherArtifical)
        self.checkBox_otherDrug = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_otherDrug.setObjectName("checkBox_otherDrug")
        self.verticalLayout_4.addWidget(self.checkBox_otherDrug)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_18.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_other)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_otherPrivFrac = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_otherPrivFrac.setObjectName("checkBox_otherPrivFrac")
        self.verticalLayout_5.addWidget(self.checkBox_otherPrivFrac)
        self.checkBox_otherSmoking = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_otherSmoking.setObjectName("checkBox_otherSmoking")
        self.verticalLayout_5.addWidget(self.checkBox_otherSmoking)
        self.checkBox_otherOsteo = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_otherOsteo.setObjectName("checkBox_otherOsteo")
        self.verticalLayout_5.addWidget(self.checkBox_otherOsteo)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_otherHipFrac = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_otherHipFrac.setObjectName("checkBox_otherHipFrac")
        self.verticalLayout_8.addWidget(self.checkBox_otherHipFrac)
        self.checkBox_otherRheumat = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_otherRheumat.setObjectName("checkBox_otherRheumat")
        self.verticalLayout_8.addWidget(self.checkBox_otherRheumat)
        self.checkBox_otherAlcohol = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_otherAlcohol.setObjectName("checkBox_otherAlcohol")
        self.verticalLayout_8.addWidget(self.checkBox_otherAlcohol)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_18.addWidget(self.groupBox_9)
        self.pushButton_otherSet = QtWidgets.QPushButton(self.groupBox_other)
        self.pushButton_otherSet.setObjectName("pushButton_otherSet")
        self.verticalLayout_18.addWidget(self.pushButton_otherSet)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.verticalLayout_14.addWidget(self.groupBox_other)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.comboBox_machineModel = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_machineModel.setObjectName("comboBox_machineModel")
        self.comboBox_machineModel.addItem("")
        self.comboBox_machineModel.addItem("")
        self.comboBox_machineModel.addItem("")
        self.comboBox_machineModel.addItem("")
        self.comboBox_machineModel.addItem("")
        self.comboBox_machineModel.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_machineModel)
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.textEdit_machinePara = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_machinePara.setObjectName("textEdit_machinePara")
        self.verticalLayout_11.addWidget(self.textEdit_machinePara)
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioButton_crossLoo = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_crossLoo.setChecked(True)
        self.radioButton_crossLoo.setObjectName("radioButton_crossLoo")
        self.horizontalLayout_12.addWidget(self.radioButton_crossLoo)
        self.radioButton_cross5per = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_cross5per.setObjectName("radioButton_cross5per")
        self.horizontalLayout_12.addWidget(self.radioButton_cross5per)
        self.radioButton_cross10per = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_cross10per.setObjectName("radioButton_cross10per")
        self.horizontalLayout_12.addWidget(self.radioButton_cross10per)
        self.radioButton_cross20per = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_cross20per.setObjectName("radioButton_cross20per")
        self.horizontalLayout_12.addWidget(self.radioButton_cross20per)
        self.radioButton_cross30per = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_cross30per.setObjectName("radioButton_cross30per")
        self.horizontalLayout_12.addWidget(self.radioButton_cross30per)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_machineSet = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_machineSet.setObjectName("pushButton_machineSet")
        self.horizontalLayout_13.addWidget(self.pushButton_machineSet)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_basicAnalysis = QtWidgets.QPushButton(OptiClassMain)
        self.pushButton_basicAnalysis.setObjectName("pushButton_basicAnalysis")
        self.horizontalLayout_8.addWidget(self.pushButton_basicAnalysis)
        self.pushButton_machineStart = QtWidgets.QPushButton(OptiClassMain)
        self.pushButton_machineStart.setObjectName("pushButton_machineStart")
        self.horizontalLayout_8.addWidget(self.pushButton_machineStart)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(OptiClassMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OptiClassMain)

    def retranslateUi(self, OptiClassMain):
        _translate = QtCore.QCoreApplication.translate
        OptiClassMain.setWindowTitle(_translate("OptiClassMain", "OptiClass"))
        self.groupBox_place.setTitle(_translate("OptiClassMain", "Place"))
        self.comboBox_region.setItemText(0, _translate("OptiClassMain", "All Region"))
        self.comboBox_region.setItemText(1, _translate("OptiClassMain", "Asia"))
        self.comboBox_country.setItemText(0, _translate("OptiClassMain", "All Country"))
        self.comboBox_country.setItemText(1, _translate("OptiClassMain", "Thailand"))
        self.comboBox_country.setItemText(2, _translate("OptiClassMain", "Japan"))
        self.comboBox_hospital.setItemText(0, _translate("OptiClassMain", "All Hospital"))
        self.comboBox_hospital.setItemText(1, _translate("OptiClassMain", "Churabhon Hospital"))
        self.comboBox_device.setItemText(0, _translate("OptiClassMain", "All Device"))
        self.comboBox_device.setItemText(1, _translate("OptiClassMain", "Device 1"))
        self.groupBox_period.setTitle(_translate("OptiClassMain", "Period"))
        self.radioButton_periodAll.setText(_translate("OptiClassMain", "All"))
        self.radioButton_period1y.setText(_translate("OptiClassMain", "1y"))
        self.radioButton_period05y.setText(_translate("OptiClassMain", "0.5y"))
        self.radioButton_period1m.setText(_translate("OptiClassMain", "1m"))
        self.radioButton_period1w.setText(_translate("OptiClassMain", "1w"))
        self.radioButton_period1d.setText(_translate("OptiClassMain", "1d"))
        self.groupBox_gender.setTitle(_translate("OptiClassMain", "Gender"))
        self.radioButton_genderAll.setText(_translate("OptiClassMain", "All"))
        self.radioButton_genderF.setText(_translate("OptiClassMain", "Female"))
        self.radioButton_genderM.setText(_translate("OptiClassMain", "Male"))
        self.groupBox_age.setTitle(_translate("OptiClassMain", "Range of age"))
        self.label.setText(_translate("OptiClassMain", "  to  "))
        self.groupBox_optdata.setTitle(_translate("OptiClassMain", "Optical data"))
        self.radioButton_optDataUlna.setText(_translate("OptiClassMain", "Ulna"))
        self.radioButton_optDataRadius.setText(_translate("OptiClassMain", "Radius"))
        self.checkBox_optDataPhantom.setText(_translate("OptiClassMain", "Phantom"))
        self.groupBox_arm.setTitle(_translate("OptiClassMain", "Measured arm"))
        self.radioButton_armAll.setText(_translate("OptiClassMain", "All"))
        self.radioButton_armLeft.setText(_translate("OptiClassMain", "Left"))
        self.radioButton_armRight.setText(_translate("OptiClassMain", "Right"))
        self.pushButton_optset.setText(_translate("OptiClassMain", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OptiClassMain", "Optical"))
        self.groupBox_bone.setTitle(_translate("OptiClassMain", "Bone"))
        self.radioButton_boneUlna.setText(_translate("OptiClassMain", "Ulna"))
        self.radioButton_boneRadius.setText(_translate("OptiClassMain", "Radius"))
        self.radioButton_boneFemur.setText(_translate("OptiClassMain", "Femur"))
        self.radioButton_boneLumbar.setText(_translate("OptiClassMain", "Lumbar"))
        self.comboBox_boneUlna.setItemText(0, _translate("OptiClassMain", "UD"))
        self.comboBox_boneUlna.setItemText(1, _translate("OptiClassMain", "33%"))
        self.comboBox_boneUlna.setItemText(2, _translate("OptiClassMain", "Total"))
        self.comboBox_boneRadius.setItemText(0, _translate("OptiClassMain", "UD"))
        self.comboBox_boneRadius.setItemText(1, _translate("OptiClassMain", "33%"))
        self.comboBox_boneRadius.setItemText(2, _translate("OptiClassMain", "Total"))
        self.comboBox_boneNeck.setItemText(0, _translate("OptiClassMain", "Neck"))
        self.comboBox_boneNeck.setItemText(1, _translate("OptiClassMain", "Upper Neck"))
        self.comboBox_boneNeck.setItemText(2, _translate("OptiClassMain", "Lower Neck"))
        self.comboBox_boneNeck.setItemText(3, _translate("OptiClassMain", "Troch"))
        self.comboBox_boneNeck.setItemText(4, _translate("OptiClassMain", "Shaft"))
        self.comboBox_boneNeck.setItemText(5, _translate("OptiClassMain", "Total"))
        self.comboBox_boneLumbar.setItemText(0, _translate("OptiClassMain", "L1"))
        self.comboBox_boneLumbar.setItemText(1, _translate("OptiClassMain", "L2"))
        self.comboBox_boneLumbar.setItemText(2, _translate("OptiClassMain", "L3"))
        self.comboBox_boneLumbar.setItemText(3, _translate("OptiClassMain", "L4"))
        self.comboBox_boneLumbar.setItemText(4, _translate("OptiClassMain", "L1-L2"))
        self.comboBox_boneLumbar.setItemText(5, _translate("OptiClassMain", "L1-L3"))
        self.comboBox_boneLumbar.setItemText(6, _translate("OptiClassMain", "L1-L4"))
        self.comboBox_boneLumbar.setItemText(7, _translate("OptiClassMain", "L2-L3"))
        self.comboBox_boneLumbar.setItemText(8, _translate("OptiClassMain", "L2-L4"))
        self.comboBox_boneLumbar.setItemText(9, _translate("OptiClassMain", "L3-L4"))
        self.comboBox_boneLumbar.setItemText(10, _translate("OptiClassMain", "Maximum Total"))
        self.pushButton_boneSet.setText(_translate("OptiClassMain", "Set"))
        self.groupBox_other.setTitle(_translate("OptiClassMain", "Other Infomation"))
        self.groupBox_8.setTitle(_translate("OptiClassMain", "Patient baisic infomation"))
        self.checkBox_otherAge.setText(_translate("OptiClassMain", "Age"))
        self.checkBox_otherHand.setText(_translate("OptiClassMain", "Dominant hand"))
        self.checkBox_otherBmi.setText(_translate("OptiClassMain", "BMI"))
        self.checkBox_otherHight.setText(_translate("OptiClassMain", "Hight"))
        self.checkBox_otherWeight.setText(_translate("OptiClassMain", "Weight"))
        self.checkBox_otherDiabates.setText(_translate("OptiClassMain", "Diabetes"))
        self.checkBox_otherDialysis.setText(_translate("OptiClassMain", "Dialysis"))
        self.checkBox_otherArmFrac.setText(_translate("OptiClassMain", "Fracture of measurement point"))
        self.checkBox_otherArtifical.setText(_translate("OptiClassMain", "Artifical bone"))
        self.checkBox_otherDrug.setText(_translate("OptiClassMain", "Drug for osteoporosis "))
        self.groupBox_9.setTitle(_translate("OptiClassMain", "FRAX®"))
        self.checkBox_otherPrivFrac.setText(_translate("OptiClassMain", "Privious fracture"))
        self.checkBox_otherSmoking.setText(_translate("OptiClassMain", "Current smoking"))
        self.checkBox_otherOsteo.setText(_translate("OptiClassMain", "Seconfary osteoporosis"))
        self.checkBox_otherHipFrac.setText(_translate("OptiClassMain", "Palental fractured hip"))
        self.checkBox_otherRheumat.setText(_translate("OptiClassMain", "Rheumatpid arthntis"))
        self.checkBox_otherAlcohol.setText(_translate("OptiClassMain", "Alcohol 3 or more units per day"))
        self.pushButton_otherSet.setText(_translate("OptiClassMain", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OptiClassMain", "Bone"))
        self.label_4.setText(_translate("OptiClassMain", "Machine learning model"))
        self.comboBox_machineModel.setItemText(0, _translate("OptiClassMain", "Gradient Boosting Classifier"))
        self.comboBox_machineModel.setItemText(1, _translate("OptiClassMain", "K-Neighbors Classifier"))
        self.comboBox_machineModel.setItemText(2, _translate("OptiClassMain", "SVC"))
        self.comboBox_machineModel.setItemText(3, _translate("OptiClassMain", "Random Forest Classifier"))
        self.comboBox_machineModel.setItemText(4, _translate("OptiClassMain", "BAgging classifier"))
        self.comboBox_machineModel.setItemText(5, _translate("OptiClassMain", "Slope classifier"))
        self.label_2.setText(_translate("OptiClassMain", "Parameter"))
        self.label_3.setText(_translate("OptiClassMain", "Cross validation"))
        self.radioButton_crossLoo.setText(_translate("OptiClassMain", "LOO"))
        self.radioButton_cross5per.setText(_translate("OptiClassMain", "5%"))
        self.radioButton_cross10per.setText(_translate("OptiClassMain", "10%"))
        self.radioButton_cross20per.setText(_translate("OptiClassMain", "20%"))
        self.radioButton_cross30per.setText(_translate("OptiClassMain", "30%"))
        self.pushButton_machineSet.setText(_translate("OptiClassMain", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("OptiClassMain", "Machine laering"))
        self.pushButton_basicAnalysis.setText(_translate("OptiClassMain", "Basic analysis"))
        self.pushButton_machineStart.setText(_translate("OptiClassMain", "Machine learning"))

